# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01c03474ab4615f952ae7f08ad7d9397007772fa20cfa21b6b26f95fdcfacc021fdd96b3883b3aa16ad61b99e52191c8c989e558c7a373cfd8911e8a65a9783

test:
  secret_key_base: c43d66ef3df908cb753d16e94276a52f600640ea1d9cba640813741d553cae70b6c2cc5cc7f55d1f3aebdb0fe21b7cbe7708f3f9af2a3ab9d4c64dd70bd3d244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: Rails.application.secrets.aws_access_key_id
  aws_secret_access_key: Rails.application.secrets.aws_secret_access_key
  
development:
  secret_key_base: ~~~~~~~~
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
